### ISSUE TITLE
suggest to rename the related shifu resources because they are confusing

### ISSUE THREAD

**Issue by ujnzxw** [Edgenesis/shifu#126]
In our project, there are some concepts such as devices, controllers, deviceshifu, etc.
But the names of these Kubernetes resources are confusing for users, such as:
1. the controller name is **crd-controller-manager** in **crd-system** namespace.
2. the device pod name is a pure device name and in **devices** namespace. 
3. the deviceshifu pod name start with **edgedevice-** and is in the default namespace.

In order to make users understand the shifu resources easily and make the components' relationship clear, I suggest renaming these resources **such as**:
1. make 2 namespaces, one named **shifu-system** which manages all the CRs, and another one named Shifu which manages the device's related resources including edge device and deviceShifu.
2. the device pod/service/ConfigMap, etc. start with "device-" in the namespace "shifu"
3. the deviceShifu pod/service/ConfigMap, etc. starts with "deviceshifu-" or "shifu-" in the namespace "shifu".
4. the controller-related resource start with "shifu-controller-" in the namespace "shifu-system".

Multi-tenant consideration:
For the resources in namespace "shifu", we also can consider just letting users decide the namespace name because the users can have permission to do resource isolation. Please consider the multi-tenant management use cases.

**Comment by tomqin93** [comment]
Closing this for now as we have renamed related resources
For ***Shifu*** component related they are in namespace `shifu-crd-system`
And for ***deviceShifu*** related they are in `deviceshifu` namespace with a `deviceshifu-` prefix for `deployment`, `service` and `configmap`
