### ISSUE TITLE
Suggestion for PLC configuration files.

### ISSUE THREAD

**Issue by su600** [Edgenesis/shifu#153]
When try to add a PLC device, 4 yaml flies are needed and serval files should be edited accordingly. 
But currently, the PLC configuration of different protocols are written in different yaml files.
Such as `Siemens-S7 IP` is written in plc-**deviceshifu-deployment.yaml**, for` OPCUA IP` is written in opcua_**edgedevice.yaml**, they are different type files.

![4eaa9235d0ec0cc11ca582af3cb238f](https://user-images.githubusercontent.com/40174401/175864475-459f472c-0f4f-4c62-ba9b-6835ca4a3489.png)

I think users or developers may feel confused when facing this situation.
So, suggest to optimize the file organization, to unify the PLC configuration in the same type file, establish a unified specification, thus whenever add a PLC,  we always know to change the same yaml file.

**Comment by tomqin93** [comment]
Hi @su600 , we have added support for this in https://github.com/Edgenesis/shifu/pull/275, we'll go ahead and close this issue now. Feel free to test and re-open if necessary !
