### ISSUE TITLE
Trouble on OPC UA device reboot

### ISSUE THREAD

**Issue by MrLeea-13155bc** [Edgenesis/shifu#188]
OPC UA's deviceshifu will always reconnect to the device many times when device is reboot, until delete the deviceshifu

**Comment by saiyan86** [comment]
@MrLeea-13155bc @tomqin93 what's the status of this?

**Comment by MrLeea-13155bc** [comment]
> @MrLeea-13155bc @tomqin93 what's the status of this?

It seems that it's a bug of gopcua package , following is the issue about the bug in gopcua/opcua's repo [https://github.com/gopcua/opcua/issues/434](https://github.com/gopcua/opcua/issues/434), we are waiting for they fix this bug.
The only way to handle this issue is closing auto-reconnect in opcua devieshifu
