### ISSUE TITLE
[feature] [deviceShifu-socket] Support multi-part reponses

### ISSUE THREAD

**Issue by smeng9** [Edgenesis/shifu#195]
Some of the device return not only a single message, but multiple messages for a single command
e.g. 
 > Calibrate
Calibrate started
(10 seconds later)
Calibrate finished

**Comment by saiyan86** [comment]
@tomqin93 Please link the corresponding PR

**Comment by tomqin93** [comment]
Will close this issue since we are not planning for this feature for now
