### ISSUE TITLE
[website]: Broken link after accepting disclaimer

### ISSUE THREAD

**Issue by smeng9** [Edgenesis/shifu#230]
Accepting disclaimer at https://shifu.run/disclaimer/ redirects to https://shifu.run/disclaimer/demo which is 404 not found

**Comment by Yang-Xijie** [comment]
It is weird that if I use `yarn build && npm run serve` to view this website, this problem doesn't appear...

**Comment by Yang-Xijie** [comment]
Fixed in https://github.com/Edgenesis/shifu-docs-docusaurus/pull/56
