### ISSUE TITLE
OPCUASetting of ProtocolSettings error 

### ISSUE THREAD

**Issue by geffzhang** [Edgenesis/shifu#260]
https://shifu.run/zh-Hans/docs/references/api/edgedevice/

![image](https://user-images.githubusercontent.com/439390/190889750-72c148b1-f70a-42a0-b9c2-38ceb2b9d84d.png)

**Comment by tomqin93** [comment]
Thanks for the issue!

**Comment by saiyan86** [comment]
@111fanyj what's the status of this?

**Comment by tomqin93** [comment]
@geffzhang  Fixed, thanks for the issue
closing this issue now
