### ISSUE TITLE
[doc] add `go documentation` in README

### ISSUE THREAD

**Issue by Yang-Xijie** [Edgenesis/shifu#302]
I saw that in some Go projects, an icon called `go documentation` is set in README.

![image](https://user-images.githubusercontent.com/57952362/194987158-8b8b5d93-2370-4c8d-b5a0-4860a9cc08e1.png)

If this project uses `godoc`, this icon could also be added.

**Comment by tomqin93** [comment]
using https://shifu.run for now, closing this issue
