### ISSUE TITLE
Support direct Shifu integration on embedded devices

### ISSUE THREAD

**Issue by kedvall** [Edgenesis/shifu#62]
We plan to move to using a standard embedded system across a number of devices. The main controller will likely be a single-board computer running a RTOS. It would save a lot of time and effort to have a set of libraries we can use to directly support and utilize Shifu features in the device.
Some examples include:
- A Shifu-aware state machine
- A way to export device-level commands to Shifu automatically
- Auto device discovery when connected / disconnected from a network
- Integration of healthcheck with hardware-level watchdog
- A standard way to query device state data and better synchronization of the digital twin and the real device

This issue is not fully developed and likely needs to be revised / updated.

**Comment by tomqin93** [comment]
Will close this issue for now since we currently have no planning for this feature
