### ISSUE TITLE
Shifu Controller should automatically create telemetryService when TelemetryService CRD presents

### ISSUE THREAD

**Issue by tomqin93** [Edgenesis/shifu#790]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Currently TelemetryService requires a Deployment and Service with [deployment YAML](https://github.com/Edgenesis/shifu/blob/main/pkg/telemetryservice/install/telemetryservice_install.yaml ) manually.

As a Shifu developer, I'd like this to happen automatically. When telemetryService CRD has been detected, Shifu Controller should automatically deploy the deployment manifests and vise versa

**Describe alternatives you've considered**

Doing it manually

**Additional context**

**Comment by lizzy-0323** [comment]
Hi, @tomqin93, I would like to work on this issue

**Comment by tomqin93** [comment]
@lizzy-0323 Thank you! You can assign this issue to yourself.
Also please contact info@edgenesis.com for your freebies!
